-- MySQL Script generated by MySQL Workbench
-- Mon Oct 18 16:10:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema horetskyi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema horetskyi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `horetskyi` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `horetskyi` ;

-- -----------------------------------------------------
-- Table `horetskyi`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horetskyi`.`rating` (
  `idrating` INT NOT NULL,
  `stars` INT NULL,
  PRIMARY KEY (`idrating`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horetskyi`.`driver`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horetskyi`.`driver` (
  `iddriver` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `number_of_cars` INT NOT NULL,
  `rating_idrating` INT NOT NULL,
  `experience` INT NOT NULL,
  PRIMARY KEY (`iddriver`),
  INDEX `fk_driver_rating1_idx` (`rating_idrating` ASC) VISIBLE,
  CONSTRAINT `fk_driver_rating1`
    FOREIGN KEY (`rating_idrating`)
    REFERENCES `horetskyi`.`rating` (`idrating`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `horetskyi`.`car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horetskyi`.`car` (
  `idcar` INT NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `mark` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `driver_iddriver` INT NOT NULL,
  `car_number` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idcar`),
  INDEX `fk_car_driver_idx` (`driver_iddriver` ASC) VISIBLE,
  CONSTRAINT `fk_car_driver`
    FOREIGN KEY (`driver_iddriver`)
    REFERENCES `horetskyi`.`driver` (`iddriver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horetskyi`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horetskyi`.`user` (
  `iduser` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `age` INT NULL,
  `gender` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `horetskyi`.`route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `horetskyi`.`route` (
  `idroute` INT NOT NULL,
  `start` VARCHAR(45) NOT NULL,
  `end` VARCHAR(45) NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `user_iduser` INT NOT NULL,
  `driver_iddriver` INT NOT NULL,
  PRIMARY KEY (`idroute`),
  INDEX `fk_route_user1_idx` (`user_iduser` ASC) VISIBLE,
  INDEX `fk_route_driver1_idx` (`driver_iddriver` ASC) VISIBLE,
  CONSTRAINT `fk_route_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `horetskyi`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_route_driver1`
    FOREIGN KEY (`driver_iddriver`)
    REFERENCES `horetskyi`.`driver` (`iddriver`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
